import * as React from 'react';

const TestTable = () => {
  const rows = [
    {
      id: '1',
      createdAt: '2023.02.22.',
      url: 'https://naver.com',
      campaignID: 'neverbs201112',
      source: 'neverbs',
      medium: 'paidsearch',
      campaignName: '20202_performance_xcategory_ecom',
      campaignTerm: 'iphone12',
      campaignContent: 'img1',
      memo: 'ㅎㅎ',
      utm: 'https://naver.com?adfkjl;aljelwrdfakjldfs',
      shorten: 'adklklsdfjl;a./dfljka;',
    },
    {
      id: '2',
      createdAt: '2023.02.22.',
      url: 'https://naver.com',
      campaignID: 'neverbs201112',
      source: 'neverbs',
      medium: 'paidsearch',
      campaignName: '20202_performance_xcategory_ecom',
      campaignTerm: 'iphone12',
      campaignContent: 'img1',
      memo: 'ㅎㅎ',
      utm: 'https://naver.com?adfkjl;aljelwrdfakjldfs',
      shorten: 'adklklsdfjl;a./dfljka;',
    },
    {
      id: '3',
      createdAt: '2023.02.22.',
      url: 'https://naver.com',
      campaignID: 'neverbs201112',
      source: 'neverbs',
      medium: 'paidsearch',
      campaignName: '20202_performance_xcategory_ecom',
      campaignTerm: 'iphone12',
      campaignContent: 'img1',
      memo: 'ㅎㅎ',
      utm: 'https://naver.com?adfkjl;aljelwrdfakjldfs',
      shorten: 'adklklsdfjl;a./dfljka;',
    },
    {
      id: '4',
      createdAt: '2023.02.22.',
      url: 'https://naver.com',
      campaignID: 'neverbs201112',
      source: 'neverbs',
      medium: 'paidsearch',
      campaignName: '20202_performance_xcategory_ecom',
      campaignTerm: 'iphone12',
      campaignContent: 'img1',
      memo: 'ㅎㅎ',
      utm: 'https://naver.com?adfkjl;aljelwrdfakjldfs',
      shorten: 'adklklsdfjl;a./dfljka;',
    },
    {
      id: '5',
      createdAt: '2023.02.22.',
      url: 'https://naver.com',
      campaignID: 'neverbs201112',
      source: 'neverbs',
      medium: 'paidsearch',
      campaignName: '20202_performance_xcategory_ecom',
      campaignTerm: 'iphone12',
      campaignContent: 'img1',
      memo: 'ㅎㅎ',
      utm: 'https://naver.com?adfkjl;aljelwrdfakjldfs',
      shorten: 'adklklsdfjl;a./dfljka;',
    },
    {
      id: '6',
      createdAt: '2023.02.22.',
      url: 'https://naver.com',
      campaignID: 'neverbs201112',
      source: 'neverbs',
      medium: 'paidsearch',
      campaignName: '20202_performance_xcategory_ecom',
      campaignTerm: 'iphone12',
      campaignContent: 'img1',
      memo: 'ㅎㅎ',
      utm: 'https://naver.com?adfkjl;aljelwrdfakjldfs',
      shorten: 'adklklsdfjl;a./dfljka;',
    },
  ];

  return <div></div>;
};

export default TestTable;
